#Download base image ubuntu 20.04
FROM ubuntu:20.04

RUN apt update 
RUN apt install -y \
    npm \
    python3-pip \  
    nodejs \
    zsh \
    vim-gtk3 \ 
    git \
    curl \
    make \
    tmux
